# docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: career_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: great
      POSTGRES_DB: career
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: